from pydantic import BaseModel, Field, field_validator


class QuoteRequest(BaseModel):
    company: str = Field(..., description="Brand/company column name from SKU_XREF, e.g. GameTime")
    sku: str = Field(..., description="Visible customer-facing SKU for the selected company")

    origin_zip: str = Field(..., min_length=3, max_length=10)
    destination_zip: str = Field(..., min_length=3, max_length=10)

    quantity: int = Field(default=1, ge=1)

    # NEW FIELDS FROM FRONTEND
    quote_number: str = Field(..., description="Unique quote identifier generated by frontend")
    customer_name: str = Field(..., description="Customer name")
    rep_name: str = Field(..., description="Sales rep requesting quote")
    project_name: str = Field(..., description="Customer project name")
    email_to: str = Field(..., description="Comma separated recipient emails")

    @field_validator("company", "sku", "origin_zip", "destination_zip",
                     "quote_number", "customer_name", "rep_name", "project_name", "email_to")
    @classmethod
    def strip_values(cls, value: str) -> str:
        return value.strip()
