from typing import List

from pydantic import BaseModel, Field, field_validator


class QuoteRequest(BaseModel):
    company: str = Field(
        ...,
        description="Brand/company column name from SKU_XREF, e.g. GameTime",
    )
    skus: List[str] = Field(
        ...,
        min_length=1,
        max_length=5,
        description="List of up to 5 visible customer-facing SKUs for the selected company",
    )

    origin_zip: str = Field(..., min_length=3, max_length=10)
    destination_zip: str = Field(..., min_length=3, max_length=10)

    quote_number: str = Field(..., description="Unique quote identifier generated by frontend")
    customer_name: str = Field(..., description="Customer name")
    rep_name: str = Field(..., description="Sales rep requesting quote")
    project_name: str = Field(..., description="Customer project name")
    email_to: str = Field(..., description="Comma separated recipient emails")

    @field_validator(
        "company",
        "origin_zip",
        "destination_zip",
        "quote_number",
        "customer_name",
        "rep_name",
        "project_name",
        "email_to",
    )
    @classmethod
    def strip_values(cls, value: str) -> str:
        return value.strip()

    @field_validator("skus", mode="before")
    @classmethod
    def normalize_skus(cls, value):
        if value is None:
            raise ValueError("At least one SKU is required.")

        if not isinstance(value, list):
            raise ValueError("SKUs must be sent as a list.")

        cleaned = [str(v).strip() for v in value if str(v).strip()]

        if not cleaned:
            raise ValueError("At least one SKU is required.")

        if len(cleaned) > 5:
            raise ValueError("A maximum of 5 SKUs is allowed.")

        lowered = [sku.lower() for sku in cleaned]
        if len(lowered) != len(set(lowered)):
            raise ValueError("Duplicate SKUs are not allowed.")

        return cleaned
